# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Vault": "00_core.ipynb",
         "starmap": "01_Early_HitTest.ipynb",
         "COLUMNS": "05_HitTest.ipynb",
         "DTYPES": "05_HitTest.ipynb",
         "DATE_COLS": "05_HitTest.ipynb",
         "DAY_FILE_PATH": "05_HitTest.ipynb",
         "get_qvals": "05_HitTest.ipynb",
         "HORIZON": "05_HitTest.ipynb",
         "HitTest": "05_HitTest.ipynb"}

modules = ["template.py",
           "starmap.py",
           "hit_test.py"]

doc_url = "https://cmorris-jacobs.github.io/jacobs-vault/"

git_url = "https://github.com/cmorris-jacobs/jacobs-vault/tree/main/"

def custom_doc_links(name): return None
