# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['Vault']

# Cell
class Vault:
    """Probably this should really be 'AIS' or 'Satellite' or some such.

    Attributes:
       att1:  uint8 (0-255)
       att2:  ufloat
    """

    core_attribute = None
    some_things = ['list', 'of', 'things']

    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __str__(self):
        return f"a = {self.a}\nb = {self.b}"

    def __repr__(self):
        return self.__str__()

    def __eq__(self, other):
        return self.a == other.a and self.b == other.b

    def solve(self):
        print("Done. That was easy!")
